#!/usr/bin/env python3
"""Normalize Codex-generated replication_info.json to the RB preregistration schema."""

from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Merge Codex-generated replication metadata into the official "
            "ReplicatorBench Python preregistration schema."
        )
    )
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Codex-generated replication_info.json",
    )
    parser.add_argument(
        "--template",
        type=Path,
        required=True,
        help="ReplicatorBench pre_registration_schema_python.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Path for the normalized replication_info.json",
    )
    return parser.parse_args()


def read_json(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(f"JSON file does not exist: {path}")

    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in {path}: {exc}") from exc

    if not isinstance(value, dict):
        raise ValueError(f"Expected a JSON object in {path}")

    return value


def merge_known_fields(template: Any, generated: Any) -> Any:
    """Overlay generated values while retaining only template-defined fields."""

    if isinstance(template, dict):
        result: dict[str, Any] = {}

        generated_dict = generated if isinstance(generated, dict) else {}

        for key, template_value in template.items():
            if key in generated_dict:
                result[key] = merge_known_fields(
                    template_value,
                    generated_dict[key],
                )
            else:
                result[key] = copy.deepcopy(template_value)

        return result

    if isinstance(template, list):
        if isinstance(generated, list) and generated:
            return copy.deepcopy(generated)
        return copy.deepcopy(template)

    if generated is not None:
        return copy.deepcopy(generated)

    return copy.deepcopy(template)


def normalize_codebase_files(value: Any) -> dict[str, str]:
    if isinstance(value, dict):
        normalized: dict[str, str] = {}

        for filename, description in value.items():
            name = str(filename).strip()
            description_text = str(description).strip()

            # Some earlier Codex runs retained the schema placeholder key
            # and placed the real filename at the start of its description.
            if name == "file_name" and description_text:
                candidate = description_text.split("—", 1)[0].strip()
                candidate = candidate.split("-", 1)[0].strip()

                if candidate.endswith(".py"):
                    name = candidate

            if not name:
                continue

            normalized[name] = (
                description_text
                or "Executable generated by Codex for the replication analysis."
            )

        return normalized

    if isinstance(value, list):
        normalized = {}

        for item in value:
            filename = str(item).strip()
            if filename:
                normalized[filename] = (
                    "Executable generated by Codex for the replication analysis."
                )

        return normalized

    raise ValueError(
        "replication_study.codebase.files must be either a list or an object"
    )


def normalize_metadata(
    generated_root: dict[str, Any],
    template_root: dict[str, Any],
) -> dict[str, Any]:
    generated_study = generated_root.get("replication_study")
    template_study = template_root.get("replication_study")

    if not isinstance(generated_study, dict):
        raise ValueError(
            "Input must contain a replication_study JSON object"
        )

    if not isinstance(template_study, dict):
        raise ValueError(
            "Template must contain a replication_study JSON object"
        )

    normalized_study = merge_known_fields(
        template_study,
        generated_study,
    )

    generated_codebase = generated_study.get("codebase", {})
    if not isinstance(generated_codebase, dict):
        generated_codebase = {}

    generated_files = generated_codebase.get("files")
    if generated_files is None:
        raise ValueError(
            "Input is missing replication_study.codebase.files"
        )

    normalized_study["codebase"]["files"] = normalize_codebase_files(
        generated_files
    )

    if "notes" not in generated_codebase:
        normalized_study["codebase"]["notes"] = (
            "Implementation independently generated by Codex in data-only mode."
        )

    generated_execution = generated_study.get("execution")
    if isinstance(generated_execution, dict):
        command = generated_execution.get("command")

        if isinstance(command, str) and command.strip():
            generated_analysis = generated_study.get("analysis")

            if not isinstance(generated_analysis, dict) or not str(
                generated_analysis.get("instructions", "")
            ).strip():
                normalized_study["analysis"]["instructions"] = (
                    f"Run `{command.strip()}` from the study input directory."
                )

    return {"replication_study": normalized_study}


def main() -> None:
    args = parse_args()

    generated = read_json(args.input)
    template = read_json(args.template)
    normalized = normalize_metadata(generated, template)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(normalized, indent=2) + "\n",
        encoding="utf-8",
    )

    print(f"Normalized metadata written to: {args.output}")


if __name__ == "__main__":
    main()
